import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next AppXX',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className="flex gap-7 fixed justify-around w-full bg-pink-500">
          <Link href="/about">CSR</Link>
          <Link href="/about">SSG</Link>
          <Link href="/about">SSR</Link>
          <Link href="/about">ISR</Link>
        </div>
        <div className="container flex flex-col items-center justify-between p-24">
          {children}
        </div>
      </body>
    </html>
  );
}
